### ISSUE TITLE
Uber bug with assets.

### ISSUE THREAD

**Issue by krukhlis** [mbrlabs/Mundus#31]
Ok, so the latest version has complitely redesigned assets manager. Which comes with lots of issues.
Please see the image attached.
![textures_loading_management_issues](https://cloud.githubusercontent.com/assets/18131621/19224120/5f2d9592-8e4d-11e6-86ff-6db8d853be99.jpg)

In short:
1) The "Assets" menu lets you load only models, not textures.
2) To load texture one can use only submenu of the button before "Gift box button".
3) One can load the same texture multiple times which is waste of the resources.
4) Assets outline shows only models, not textures. :(

**Comment by mbrlabs** [comment]
1) The Assets menu in the menu bar does nothing, it shows all assets unfiltered for debugging reasons
2) Yes, you can import new textures and models there
3) What do you mean multiple times. Sure, you can import the same asset multiple times if you choose. But the asset manager loads the resource only once if you open the project.
4) Yes, it shows only models. That's intended

A few more notes:
- You can apply textures to models independtly now (see the ModelComponent in the outline).
- If you select a resource from the assets dialog, the resource is not loaded again. With the dialog you can only select a reference to that asset.
- You can specify filters on the asset dialog, that's why some assets are somtimes not visible. E.g if you select a new texture for a model, the asset dialog will only show texture assets
- It's not finished yet ;)

**Comment by krukhlis** [comment]
Regarding 3)
So I can import multiple times the same texture. And in assets browser I will see multiple lines with this texture:
![mundus-assets1](https://cloud.githubusercontent.com/assets/18131621/19224839/129613a8-8e5c-11e6-9f2e-8c99b298a074.jpg)
And I can use any of this as texture for my model. However, if save the project and reload Mundus --
I see the texture was loaded only once and I have only 1 entyry in assets browser:
![mundus-assets2](https://cloud.githubusercontent.com/assets/18131621/19224872/718418ce-8e5c-11e6-9b29-596dbe0af87e.jpg)

 Which is inconsistent with the original situation. :)

**Comment by mbrlabs** [comment]
Oh yes, that's a bug ;)
It's overriding the files when importing the asset for the second time. That's why they are gone after the restart. We need to check if there already exists a file with that name and if yes, add an extension to the filename. Or just forbid to import a new asset with the same name.
I'd prefer the second option, because it better reflects the organistion in folders.

I'll do that tomorrow.

**Comment by krukhlis** [comment]
I also agree with the second option, cool!

**Comment by mbrlabs** [comment]
Alright, i fixed the bug by preventing the user to import multiple assets with the same name.
